// This file would typically be auto-generated by the Amplify CLI
// For manual setup, you can create this file with your AWS Cognito configuration

const awsmobile = {
  aws_project_region: 'us-east-2',  // Replace with your AWS region
  aws_cognito_region: 'us-east-2',  // Replace with your AWS region
  aws_user_pools_id: 'us-east-2_RtsHTy5JO', // Replace with your User Pool ID
  aws_user_pools_web_client_id: '7rkpv9oq4aj13edeimac9i4bks', // Replace with your App Client ID
  oauth: {
    domain: 'us-east-2rtshty5jo.auth.us-east-2.amazoncognito.com', // Your Cognito domain
    scope: ['email', 'profile', 'openid'], 
    redirectSignIn: 'https://staging.d28409e8zobsxb.amplifyapp.com', // Fixed redirect URL
    redirectSignOut: 'https://staging.d28409e8zobsxb.amplifyapp.com', // Same as redirectSignIn
    responseType: 'code',
    federationTarget: 'COGNITO_USER_POOLS'
  },
  aws_cognito_username_attributes: ['EMAIL'],
  aws_cognito_social_providers: ['GOOGLE'],
  aws_cognito_signup_attributes: ['EMAIL', 'NAME'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: [],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: []
  },
  aws_cognito_verification_mechanisms: ['EMAIL']
};

export default awsmobile;